name: test
on:
  pull_request:
    branches: [main]
    paths:
      - '**.tsx?'
      - '**.test.ts'

env:
  NODE_ENV: dev
  ACTIONS_ALLOW_UNSECURE_COMMANDS: ${{ secrets.ACTIONS_ALLOW_UNSECURE_COMMANDS }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: run test
        run: |
          npm install
          npm run test:all
